name: deliveryui
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  geolocator: ^11.1.0
  permission_handler: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
